name: CI
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # GitHub 리포지토리를 체크아웃
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Node.js를 설정합니다. 저는 버전 18을 사용합니다.
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # SSH 접속 키 파일을 저장해줍니다.
      - name: Register SSH Host Key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.BUILD_SSH_PORT }} -H ${{ secrets.BUILD_SSH_IP }} 2>&1 | tee -a ~/.ssh/known_hosts

      # 원격 서버에 SSH로 접근하여 배포 작업을 수행합니다. 
      - name: Deploy to Server
        env:
          DEPLOY_SSH_KEY: ${{ secrets.SSH_PEM }}
          BUILD_SSH_IP: ${{ secrets.BUILD_SSH_IP }}
          BUILD_SSH_USER: ${{ secrets.BUILD_SSH_USER }}
        run: |
          # SSH 키 설정을 수행합니다.
          mkdir -p ~/.ssh
          echo "$DEPLOY_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # 빌드 서버에 SSH로 접근하여 배포 스크립트를 실행합니다.
          # 여기서는 사용자 정의 스크립트 './start_backend.sh'를 실행합니다.
          ssh -v -i ~/.ssh/id_rsa $BUILD_SSH_USER@$BUILD_SSH_IP "./start_backend.sh"
